Yakushev 24 06 filter feature
kvandotech/popsters pull request #24
Opened 2021-06-25 08:26 UTC by PRO100Spike

Добавил фильтры по дате и тексту + поиск по дате и тексту

2021-06-25 13:32 UTC, FominSergey5869 approved these changes

2021-06-28 07:30 UTC, khigor777 requested changes

2021-06-28 07:30 UTC, khigor777 commented on src/components/posts/element.jsx
> +                          ? filter.condition === 1
All digits should be moved to constants

2021-06-28 07:30 UTC, khigor777 commented on src/utils/filter-feed.js
> +            if (filter.condition === 1) {
All digits should be moved to constants

2021-06-28 07:30 UTC, khigor777 commented on src/utils/filter-feed.js
> +            if (filter.condition === 2) {
All digits should be moved to constants

2021-06-28 07:30 UTC, khigor777 commented on src/utils/filter-feed.js
> +        if (filter.condition > 0) {
All digits should be moved to constants

2021-06-28 07:30 UTC, khigor777 commented on src/utils/filter-feed.js
> +        if (filter.condition > 0)
All digits should be moved to constants

2021-06-28 07:30 UTC, khigor777 commented on src/redux/group-reducer.js
>        if (condition === 2) condition = 0
All digits should be moved to constants

2021-06-28 11:53 UTC, khigor777 approved these changes

2021-06-28 12:30 UTC, merged